### PR TITLE
Sanitize job names

### LINKED ISSUE #172: Add ability to sanitize job name in PBSPro and Grid Engine adapter
In some deployments of Grid Engine, special characters such as slash are not allowed in job names. This causes problems when submitting interactive apps, where we use slashes in the job name.

See https://github.com/OSC/ondemand/issues/341 and in particular https://github.com/OSC/ondemand/issues/341#issuecomment-567733351.

Suggested solution https://github.com/OSC/ondemand/issues/341#issuecomment-570267574

### PR DESCRIPTION
**Pull request by MorganRodgers**
Fixes #172.

### CODE REVIEW

**Comment by ericfranz** [comment]
Instead of a config option and force sanitizing every job submission... this might be a better alternative https://github.com/OSC/ood_core/issues/172#issuecomment-571255666

Then this method could be used instead of `parameterize.underscore`...

**Comment by MorganRodgers** [comment]
I'm confused by the recommendations. For context the linked alternative:

> An `Adapter#sanitize_job_name(job_name)` method could be added whose default implementation just returns the job name in question. Minimally, that could be used in places where we submit jobs to first sanitize the job name.

I do not understand the utility of adding a super class implementation. Adding another method with a default implementation only extends the `Adapter` interface. We do still want a configuration option because presumably there are PBSPro and GE sites that do not have this problem, otherwise I would have expected that we would have heard about this sooner, and if a site is not experiencing the issue then we do not want/need to change OnDemand's behavior.

Just so I am clear your comment:

> Then this method could be used instead of `parameterize.underscore`...

By `this method` you are referencing the replacement of non-ASCII (or whatever the illegal characters set is) with underscores?

**Comment by ericfranz** [comment]
If that method exists, then instead of https://github.com/OSC/ondemand/pull/364/files#diff-9ddf794da41002473c7abf3dc34e48d5R425

we could do something like

```ruby
def job_name
  [
    ENV["OOD_PORTAL"].to_s,
    ENV["RAILS_RELATIVE_URL_ROOT"].to_s.sub(/^\/[^\/]+\//, ""),
  ].reject(&:blank?).join("/").tap do |jb_nm|
    adapter.sanitize_job_name(jb_nm)
  end
end
```

**Comment by ericfranz** [comment]
It is an alternative to the approach of providing a configuration flag that if enabled we always sanitize. But I guess that there are reasons we discussed offline where we might want to always sanitize every job name set...

**Comment by ericfranz** [comment]
Opted for a simpler approach for now https://github.com/OSC/ood_core/pull/183 will revisit this more robust approach later.

**Pull request closed without merging**
