### PR TITLE
Lsf Adapter Updates

### LINKED ISSUE #22: LSF Adapter: add "estimated runtime" by subtracting current time from start time
It is an estimate. If the job is never suspended after starting, this will be accurate.

LSF 9+ offers the ability to modify the output of the bjobs and specify runtime in the output. So we will be able to provide a more accurate runtime for later versions at that time.

This will allow an empty column in Active Jobs to be set with a value.

### PR DESCRIPTION
**Pull request by ericfranz**
Fixes #22 and #25 and #27

### CODE REVIEW

**Comment by nickjer** [comment]
Seems you are missing from the submission arguments `Script#email`

Quick question, does it really submit to the command line `-B true`, `-B false`, `-N true`, and `-N false` for the email on started and terminated?

**Comment by nickjer** [comment]
Also I noticed this:

>-o output_file
>Specify a file path. Appends the standard output of the job to the specified file. Sends the output by mail if the file does not exist, or the system has trouble writing to it.
>
>-oo output_file
>Specify a file path. Overwrites the standard output of the job to the specified file if it exists, or sends the output to a new file if it does not exist. Sends the output by mail if the system has trouble writing to the file.

Do we want to append to the output file or write over it if it exists? I am assuming Torque and Slurm write over the output file it exists, but now that I think about it I never tested it.

**Comment by nickjer** [comment]
Nevermind, it seems Torque actually appends output files as well. Hah, I never knew that.

**Comment by ericfranz** [comment]
Good find on the email and email flags. I'll fix that.

**Comment by ericfranz** [comment]
@nickjer final chance to review this before I merge it!

**Comment by nickjer** [comment]
Sure, go ahead. If anymore bugs show up we can just patch them.

**Pull request merged**
