### PR TITLE
Catch expections in parsing bad and empty cluster files

### LINKED ISSUE #150: Catch exceptions when reading bad cluster yml files
We've gotten issues from users of this library (ourselves in the Ondemand dashboard) where exceptions are thrown from reading invalid yml files for cluster configs.

The offending read line is [here](https://github.com/OSC/ood_core/blob/869cd93878c30ae4fc9f469f062b9452d94b61b4/lib/ood_core/clusters.rb#L31) and the solution seems simply to catch (rescue in ruby parlance) the exception, spitting out the relevant message in logs. 
```ruby
          Pathname.glob(config.join("*.yml")).each do |p|
            CONFIG_VERSION.any? do |version|
              if cluster = YAML.safe_load(p.read).fetch(version, nil)
                clusters << Cluster.new(send("parse_#{version}", id: p.basename(".yml").to_s, cluster: cluster))
                true
              else
```

### PR DESCRIPTION
**Pull request by johrstrom**
This can catch Psych::SyntaxError while parsing a malformed cluster definition file and safely traverse empty cluster definitions.  This tries to fix #150 and #178. 

Most uses of Clusters filter off of `allow?` or `custom_allow?` and the InvalidCluster doesn't allow for anything so most (if not all) uses of clusters will filter these types out. 

Right now the only things you can really rely on are the `id` and `metadata.error_msg`.

### CODE REVIEW

**Comment by johrstrom** [comment]
notes from discussion

* add a valid? api
*

**Comment by johrstrom** [comment]
I added the `valid?` where clusters always return true and invalid_clusters always return false.

We had talked about adding an `error_msg` API too instead of holding the error message in metadata. Do you have more thoughts on that?  I only hesitated just as a reaction against expanding API further, but I'm happy to add it directly instead of burying it within metadata.

**Comment by ericfranz** [comment]
One consideration is adding an API similar to ActiveModel validations i.e. https://api.rubyonrails.org/classes/ActiveModel/Errors.html. Not in the sense that in ActiveModel::Errors the error messages are tied to attributes. Rather, in the sense that `Cluster#errors` could be a hash or an array with one or more problems. It could be a simple as an array of strings, that by default is empty.

The reason is that you could have a valid cluster config, (valid yaml, minimum data required is there) but a section of it could be indented incorrectly and thus omitted (job section is indented incorrectly, so job management is not configured for the cluster).

Of course that type of validation and help is something that would be nice to do but we can save for the future. So if we extended the API at all that is what I would do.

**Comment by ericfranz** [comment]
An example use of that would be a valid cluster config with "errors" would display using warning, and invalid cluster config would use error alert on dashboard.

**Comment by johrstrom** [comment]
Done! I guess a hash would be better, then you could give severity? or we could add a `warnings` later to indicate errors are fatal and warnings, are well.. warnings. 

In any case, I've set it to an array of strings, if you want the hash instead just let me know.

**Pull request merged**
